# Properties may be overridden in this optional properties file.
spring.config.import=optional:classpath:env.properties
spring.application.name=avenirs-portfolio-back-office
spring.profiles.active=prod
server.address=0.0.0.0
server.port=10010
server.url=http://localhost:10010
# Security
security.permit-all-paths=/actuator/prometheus,/actuator/health,/actuator/caches,/avenirs-portfolio-back-office/api-docs/**,/avenirs-portfolio-back-office/swagger-ui/**,/favicon.ico,/actuator/health,/photo/**,/cover/**,/storage/**,/error
# Persistence
spring.datasource.url=jdbc:postgresql://localhost:65432/avenirs_back_office
spring.datasource.username=avenirs_back_office_admin
spring.datasource.password=ENC(35gvyDVeasprFzTNQvTjl1HAMjTb5Zcu)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default-schema=dev
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=false
spring.liquibase.default-schema=dev
# Hikari
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1
# jasypt
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.password=${jasypt-encryptor-password}
# Prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.api-docs.path=/avenirs-portfolio-back-office/api-docs
springdoc.swagger-ui.path=/avenirs-portfolio-back-office/swagger-ui
# CORS Configuration
cors.allowed-origins=*
cors.allowed-methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
cors.allowed-headers=*
cors.allow-credentials=false
