spring.application.name=avenirs-portfolio-back-office
server.port=8083
server.servlet.context-path=/avenirs-portfolio-back-office
spring.datasource.url=jdbc:postgresql://localhost:65432/avenirs_back_office
spring.datasource.username=avenirs_back_office_admin
spring.datasource.password=ENC(nrhrW8giUqCjQzWRBDVj/XYVStp8Tgxs)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default-schema=dev
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
spring.liquibase.default-schema=dev
jasypt.encryptor.algorithm=PBEWithMD5AndDES
jasypt.encryptor.iv-generator-classname=org.jasypt.iv.NoIvGenerator
jasypt.encryptor.password=${jasypt-encryptor-password}
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
