changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml
outputFileEncoding=UTF-8

# Reference
referenceUrl=hibernate:spring:fr.avenirsesr.portfolio.backoffice.shared.infrastructure.adapter.model?dialect=org.hibernate.dialect.PostgreSQLDialect
referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver

# DB
url=jdbc:postgresql://localhost:65432/avenirs_back_office
username=avenirs_back_office_admin
password=ENC(35gvyDVeasprFzTNQvTjl1HAMjTb5Zcu)
driver=org.postgresql.Driver
defaultSchemaName=dev

log-level=debug
